from enum import IntEnum
from fastapi import status


class HTTP_STATUS(IntEnum):
    OK = status.HTTP_200_OK
    CREATED = status.HTTP_201_CREATED
    BAD_REQUEST = status.HTTP_400_BAD_REQUEST
    UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
    FORBIDDEN = status.HTTP_403_FORBIDDEN
    NOT_FOUND = status.HTTP_404_NOT_FOUND
    CONFLICT = status.HTTP_409_CONFLICT
    TOO_MANY_REQUESTS = status.HTTP_429_TOO_MANY_REQUESTS
    INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
    NOT_IMPLEMENTED = status.HTTP_501_NOT_IMPLEMENTED
    VALIDATION_ERROR = status.HTTP_422_UNPROCESSABLE_ENTITY
    SERVICE_UNAVAILABLE = status.HTTP_503_SERVICE_UNAVAILABLE
    DATABASE_CONNECTION_FAILED = status.HTTP_503_SERVICE_UNAVAILABLE

    # 💡 Custom business-level codes (not true HTTP but logical wrappers)
    EMAIL_VERIFICATION_REQUIRED = 428  # HTTP_428_PRECONDITION_REQUIRED
    INVALID_COUPON = 460               # Custom non-standard code
    DATA_EXISTS = 461                  # Custom non-standard code
    USER_ALREADY_EXISTS = 462          # Custom non-standard code
    USERNAME_ALREADY_EXISTS = 463      # Custom non-standard code


HTTP_CODE = {
    "OK": "OK",
    "CREATED": "CREATED",
    "BAD_REQUEST": "BAD_REQUEST",
    "UNAUTHORIZED": "UNAUTHORIZED",
    "FORBIDDEN": "FORBIDDEN",
    "NOT_FOUND": "NOT_FOUND",
    "CONFLICT": "CONFLICT",
    "TOO_MANY_REQUESTS": "TOO_MANY_REQUESTS",
    "INTERNAL_SERVER_ERROR": "INTERNAL_SERVER_ERROR",
    "NOT_IMPLEMENTED": "NOT_IMPLEMENTED",
    "VALIDATION_ERROR": "VALIDATION_ERROR",
    "SERVICE_UNAVAILABLE": "SERVICE_UNAVAILABLE",
    "DATABASE_CONNECTION_FAILED": "DATABASE_CONNECTION_FAILED",
    "EMAIL_VERIFICATION_REQUIRED": "EMAIL_VERIFICATION_REQUIRED",
    "INVALID_COUPON": "INVALID_COUPON",
    "DATA_EXISTS": "DATA_EXISTS",
    "USER_ALREADY_EXISTS": "USER_ALREADY_EXISTS",
    "USERNAME_ALREADY_EXISTS": "USERNAME_ALREADY_EXISTS",
}
